USE [master]
GO
CREATE LOGIN [DnDLogin] WITH PASSWORD=N'Natural1', DEFAULT_DATABASE=[master], CHECK_EXPIRATION=OFF, CHECK_POLICY=OFF
GO
ALTER SERVER ROLE [dbcreator] ADD MEMBER [DnDLogin]
GO
ALTER SERVER ROLE [sysadmin] ADD MEMBER [DnDLogin]
GO