USE DndDb
BEGIN TRANSACTION;
CREATE TABLE SourceID(
ID int NOT NULL,
SourceType VARCHAR(30) NOT NULL,
)

INSERT INTO SourceID (ID, SourceType)
VALUES
(0, 'PHB 5TH EDITION CONTENT'),
(1, 'HOMEBREW CONTENT'),
(2, 'ONLINE CONTENT'),
(3, 'OTHER SOURCE CONTENT')
SELECT * FROM SourceID

--COMMIT
--ROLLBACK